ahoyapi: v2
usage: Commands
commands:

  setup:
    usage: Clone Drupal and stuff
    cmd: |
      lando stop
      composer install
      chmod -Rf 755 91x/sites/default
      rm -rf 91x
      git clone https://git.drupalcode.org/project/drupal.git --depth=3 --branch=9.1.x 91x
      ahoy reset

  reset:
    usage: Resets core ready for a new patch, leaving the site installed.
    cmd: |
      cd 91x
      chmod -Rf 775 sites/default
      git stash
      git reset --hard
      git clean -fd
      git checkout 9.1.x
      git pull
      git status
      cp example.gitignore .gitignore
      echo ".gitignore" >> .gitignore
      #echo "core/phpunit.xml" >> .gitignore
      composer install

  reset-sites-default:
    usage: Remove and reset anything in sites/default.
    cmd: |
      ahoy fix-perms
      rm -Rf 91x/sites/default
      cd 91x
      git checkout sites/default
      mkdir sites/default/files

  fix-perms:
    usage: Tries to fix file perms.
    cmd: |
      echo "... fixing sites/default permission."
      chmod -f 777 91x/sites
      chmod -Rf 777 91x/sites/default

  install:
    usage: Does a fresh Drupal install
    cmd: |
      ahoy reset-sites-default
      cp ./templates/settings.php 91x/sites/default/settings.php
      cp ./templates/services.yml 91x/sites/default/services.yml
      lando drush --root=/app/91x site:install --yes
      ahoy fix-perms
      lando drush --root=/app/91x --uri=https://coredev.lndo.site uli
      lando drush --root=/app/91x cr
      cd 91x && git checkout sites/default # Install removes some files we don't want to show as dirty in git.

  drush:
    usage: Drush command against the site
    cmd: |
      lando drush --root=/app/91x --uri=https://coredev.lndo.site "$@"
      # Avoids getting drush stuck in the container when you switch back to web.
      lando drush --root=/app/91x cr

  apply:
    usage: Apply a patch from a URL
    cmd: |
      cd 91x
      curl "$@" | git apply -v
      git status

  roll:
    usage: Role a patch, with a file name.
    cmd: |
      cd 91x
      git diff > ../patches/"$@".patch
