name: coredev
recipe: drupal9
config:
  php: '7.3'
  via: nginx
  database: mariadb
  webroot: 91x

services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=appserver"
        SIMPLETEST_DB: "mysql://drupal:drupal@testdb/drupal"
        SIMPLETEST_BASE_URL: "http://coredev.lndo.site"

  database:
    type: mysql
    creds:
      user: drupal
      password: drupal
      database: drupal
  testdb:
    type: mysql
    creds:
      user: drupal
      password: drupal
      database: drupal
